version: '3.1'
services:
  app:
    build:
      dockerfile: ./docker/Dockerfile
      context: .
    container_name: 'bot_app'
    restart: always
    links:
      - postgres
    command: "python bot.py"
#  worker:
#    build:
#      dockerfile: ./docker/Dockerfile
#      context: .
#    container_name: 'bot_worker'
#    restart: always
#    links:
#      - postgres
#    command: "python worker.py"
  postgres:
    image: postgres:latest
    container_name: 'bot_db'
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}